# Generated by Django 3.2.9 on 2021-12-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_event_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(max_length=1000)),
                ('is_verified', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
