# Generated by Django 3.2.9 on 2021-12-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_payment_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
