# Generated by Django 3.2.9 on 2021-12-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_alter_payment_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='transaction_id',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
