# Generated by Django 3.2.9 on 2022-01-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_auto_20211228_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='transaction_id',
            field=models.CharField(help_text='Enter transaction id here, transaction id will be provided by your service provider i.e EasyPaisa provide you through sms over a successful transaction', max_length=1000, unique=True),
        ),
    ]
