# Generated by Django 4.0.5 on 2022-06-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_alter_event_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='double_split',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='music',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='red_carpet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='single_split',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='triple_split',
            field=models.BooleanField(default=False),
        ),
    ]
