# Generated by Django 3.2.9 on 2021-11-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text='This account belongs to Moderator/Teacher'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='This account is parental'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, height_field='150', help_text='Profile image must be 150*150 in size of png, jpg or jpeg', null=True, upload_to='images/profiles/', verbose_name='Profile Picture', width_field='150'),
        ),
    ]
