# Generated by Django 3.2.9 on 2021-11-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='institute',
        ),
    ]
